### ISSUE TITLE
Moving towards 5e

### ISSUE THREAD

**Issue by DonaldTsang** [dyslexic-charactersheets/pages#12]
Same note as https://github.com/dyslexic-charactersheets/assets/issues/4 but since the resources are scattered between repos, it might be a good idea to make an issue.

**Comment by marcus-downing** [comment]
> It might be a good idea to include 5e PDFs since people are moving away from 3.5e.

First, my hands are full with the transition to Pathfinder 2e at the moment, so I can't even consider starting on any other games until that's complete.

Even then, I'm not convinced there's a pressing need for 5e. It's been out for six years now (I kind of missed the boat when it was new), and plenty of people have made their own custom character sheets for it already, including class-specific ones. It's a much simpler system too, so I'm not certain I'd be adding much. If I had unlimited time and energy then I'd work on this, but since I don't I have to consider where my energy is best spent, and I'm not sure 5e is it.

Of course, if Wizards released a 6th edition, or even a 5.5, then I'd reconsider that. But there's little sign of that right now, while 5th is doing so well for them.

**Comment by DonaldTsang** [comment]
As a person with reading problems, since I have been introduced to 5e directly, that is my only frame of reference. I would like to apologize in advance that you are currently busy, but I do hope that the dyslexic character sheet for 5e can be done as soon as possible. If there are other sources for such a sheet, do link them here.

**Comment by marcus-downing** [comment]
For reasons that should be obvious, I will not be making anything for 5e or any other WotC game, unless they significantly change their ways.
