### ISSUE TITLE
macOS system files

### ISSUE THREAD

**Issue by computergeek125** [dyslexic-charactersheets/pages#3]
On macOS, when you open a folder in Finder (equivalent to Windows Explorer), it leaves behind a small binary file named `.DS_Store` that tells Finder the last used view settings (icon arrangement, sorting, etc.).  

Would you be able to add this file to the `.gitignore`?

```diff
diff --git a/.gitignore b/.gitignore
index 084d090..49180a2 100644
--- a/.gitignore
+++ b/.gitignore
@@ -11,3 +11,4 @@ Scripts/Illustrator script.log
 Isometric A4.ai
 Old
 Illustrator script.log
+.DS_Store
```

**Comment by marcus-downing** [comment]
Good idea. I should do that to all the repos.

On 10 Apr 2017 5:23 p.m., "Ryan Smith" <notifications@github.com> wrote:

On macOS, when you open a folder in Finder (equivalent to Windows
Explorer), it leaves behind a small binary file named .DS_Store that tells
Finder the last used view settings (icon arrangement, sorting, etc.).

Would you be able to add this file to the .gitignore?

diff --git a/.gitignore b/.gitignore
index 084d090..49180a2 100644--- a/.gitignore+++ b/.gitignore@@ -11,3
+11,4 @@ Scripts/Illustrator script.log
 Isometric A4.ai
 Old
 Illustrator script.log+.DS_Store

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dyslexic-charactersheets/pages/issues/3>, or mute the
thread

**Comment by marcus-downing** [comment]
I've added `.DS_Store` to this repo, and I'll add it to the others.
